USE master;
DROP DATABASE QuanLyCuaHangBanGiay;
CREATE DATABASE QuanLyCuaHangBanGiay;
USE QuanLyCuaHangBanGiay;

CREATE TABLE TaiKhoan (
	TenTK NVARCHAR(100) PRIMARY KEY,
	MatKhau NVARCHAR(100),
	MaNV INT,
	ChucVu NVARCHAR(50)
);

CREATE TABLE KhachHang (
	MaKH INT IDENTITY PRIMARY KEY,
	TenKH NVARCHAR(100), 
	GioiTinh BIT, 
	DiaChi NVARCHAR(200),
	Email NVARCHAR(50), 
	SoDT NVARCHAR(10)
);

CREATE TABLE HoaDon (
	MaHD INT IDENTITY PRIMARY KEY,
	MaKH INT, 
	NgayMua DATE,
	TrangThai NVARCHAR(50), 
	PTTT NVARCHAR(40),
	FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
		ON DELETE CASCADE 
		ON UPDATE CASCADE
);

CREATE TABLE ChiTietHoaDon (
	MaCTHD INT IDENTITY PRIMARY KEY,
	MaHD INT,
	MaSP INT,
	SoLuong INT, 
	DonGiaBan DECIMAL(18, 2),
	FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE DanhMuc (
	MaDM INT IDENTITY PRIMARY KEY,
	TenDM NVARCHAR(100)
);

CREATE TABLE SanPham (
	MaSP INT IDENTITY PRIMARY KEY,
	TenSP NVARCHAR(100),
	DonGiaNhap DECIMAL(18, 2),
	DonGiaBan DECIMAL(18, 2),
	MaDM INT,
	FOREIGN KEY (MaDM) REFERENCES DanhMuc(MaDM)
		ON DELETE CASCADE 
		ON UPDATE CASCADE
);

CREATE TABLE NhanVien (
	MaNV INT IDENTITY PRIMARY KEY,
	TenNV NVARCHAR(100),
	GioiTinh BIT, 
	DiaChi NVARCHAR(200),
	Email NVARCHAR(50), 
	SoDT NVARCHAR(10),
	username NVARCHAR(100),
);

CREATE TABLE NhaCungCap (
	MaNCC INT IDENTITY PRIMARY KEY,
	TenNCC NVARCHAR(50),
	DiaChi NVARCHAR(200),
	Email NVARCHAR(50), 
	SoDT NVARCHAR(10)
);

CREATE TABLE HoaDonNhap (
	MaHDN INT IDENTITY PRIMARY KEY,
	MaNCC INT,
	MaNV INT, 
	NgayNhap DATE,
	TrangThai NVARCHAR(50),
	FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
		ON DELETE CASCADE 
		ON UPDATE CASCADE,
	FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
		ON DELETE CASCADE 
		ON UPDATE CASCADE
);

CREATE TABLE ChiTietHoaDonNhap (
	MaSP INT,
	MaHDN INT,
	SoLuong INT,
	DonGiaNhap DECIMAL(18, 2),
	FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
		ON DELETE CASCADE 
		ON UPDATE CASCADE,
	FOREIGN KEY (MaHDN) REFERENCES HoaDonNhap(MaHDN)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

ALTER TABLE ChiTietHoaDon 
ADD CONSTRAINT Fk_CTHD_SP
FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP);

ALTER TABLE TaiKhoan 
ADD CONSTRAINT Fk_NV_TK
FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV);

